### PR TITLE
Django 2.2 compatibility fix

### PR DESCRIPTION
**Pull request by arbrandes**
This allows the plugin to run under Django 2.2.

### CODE REVIEW

**Comment by jmbowman** [comment]
Is any assistance needed to get this reviewed, merged, and released?

**Comment by bradenmacdonald** [comment]
@jmbowman I'll merge this later today and then will need your help merging the version bump PR in `configuration`. Will ping you.

**Comment by bradenmacdonald** [comment]
:+1:

- [x] I tested this: tested backwards-compatibility w/ Django 1.11; code change is well-known and I'll trust your test on 2.2
- [x] I read through the code
- [x] I checked for accessibility issues: n/a
- [x] Includes documentation: n/a

**Comment by bradenmacdonald** [comment]
@arbrandes BTW I fixed your permissions; please push to the `open-craft` repo in the future and not a fork.

**Comment by arbrandes** [comment]
> @arbrandes BTW I fixed your permissions; please push to the `open-craft` repo in the future and not a fork.

Got it, thanks.

**Pull request merged**
