### PR TITLE
[FAL-3510] Remove db table and it's reference

### PR DESCRIPTION
**Pull request by pkulkark**
## Description

This PR removes the DB table for pathway and all it's reference, adding a drop table migration.

## Supporting information
OpenCraft Internal Jira ticket: [FAL-3510](https://tasks.opencraft.com/browse/FAL-3510)

### CODE REVIEW

**Review by awais786 — APPROVED** [review]

**Comment by awais786** [comment]
@pkulkark Please merge it.

**Comment by pkulkark** [comment]
Thanks @awais786. I don't seem to have the permission to merge this. Could you merge it?

**Comment by awais786** [comment]
@symbolist please merge this. We don't have merging rights.

**Comment by symbolist** [comment]
@pkulkark @awais786 Sure, done. 🙂

**Comment by awais786** [comment]
@pkulkark @symbolist  we face one issue on sandbox.
`pip install -e git+https://github.com/labxchange/lx-pathway-plugin.git@a3ad45267da4c447bd79e41150303957203a3227#egg=lx-pathway-plugin`

1. `python manage.py cms migrate` runs fine but it will not remove the table.

2. `python manage.py lms migrate` gives following error.  Since both commands runs on pipelines so lms migrate will break it.

Now I am thinking it might be divide into 2 prs. One PR drop the tables+model only and then in 2nd remove the code.

```
Traceback (most recent call last):
  File "manage.py", line 106, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/edx/app/edxapp/edx-platform/lms/urls.py", line 994, in <module>
    urlpatterns.extend(get_plugin_url_patterns(ProjectType.LMS))
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/edx_django_utils/plugins/plugin_urls.py", line 34, in get_plugin_url_patterns
    return [
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/edx_django_utils/plugins/plugin_urls.py", line 35, in <listcomp>
    _get_url(url_module_path, url_config)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/edx_django_utils/plugins/plugin_urls.py", line 24, in _get_url
    return re_path(regex, include((url_module_path, app_name), namespace=namespace))
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/edx/app/edxapp/venvs/edxapp/src/lx-pathway-plugin/lx_pathway_plugin/urls_lms.py", line 11, in <module>
    url(r'pathway/(?P<pathway_key_str>[^/]+)/$', views.PathwayView.as_view()),
AttributeError: module 'lx_pathway_plugin.views' has no attribute 'PathwayView'
````

**Comment by awais786** [comment]
My bad I did't notice. Need to add a delete `migration`. You need to revert this PR and then make new one.

Steps:

1. remove model
2. run makemigrations
3. push the new migration.
4. samle PR https://github.com/irtazaakram/lx-pathway-plugin/pull/1/files

**Comment by symbolist** [comment]
@awais786 I have reverted this in https://github.com/labxchange/lx-pathway-plugin/pull/18. Since you already have this set up, if you can create the PR from your fork against this repo, we can just merge that in? 

CC @pkulkark

**Comment by symbolist** [comment]
Okay, I see you already have https://github.com/open-craft/lx-pathway-plugin/pull/3 open.

**Pull request merged**
